library(AIExam)
# command click the function names in RStudio to jump to the code!
AIExam::makeQuestionAStar()
AIExam::makeQuestionAlphaBeta()
AIExam::makeQuestionCNN()
AIExam::makeQuestionFFNN()
AIExam::makeQuestionHMM_FB()
AIExam::makeQuestionHMM_Vit()
AIExam::makeQuestionMCMC()
AIExam::makeQuestionMultiArmedBandit()
AIExam::makeQuestionSchedule()
AIExam::makeTextQuestions()
